# Tarea 5 Estructuras de datos: Listas

### Curso Python de la A a la Z

### Ejercicio 1
Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
finalmente muestre la secuencia invertida.

In [5]:
caracteres = input("Ingrese una secuencia de caracteres: ")
lista = []
for i in caracteres:
    lista.append(i)
lista.reverse()
print("Secuencia invertida: {}".format(lista))

Ingrese una secuencia de caracteres: Hola
Secuencia invertida: ['a', 'l', 'o', 'H']


### Ejercicio 2
Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
mostrar el contenido de la lista.
Por ejemplo, si introducimos **hola caracola** y **adios marieta**, debería mostrarse **haodleao sc
amraarcioeltaa**.

In [8]:
str1 = input("Ingrese una cadena de caracteres: ")
str2 = input("Ingrese otra cadena de caracteres: ")
k = 1
lista = []

while len(str1) != len(str2):
    print("Los dos strings deben tener la misma longitud. Intente nuevamente.")
    str1 = input("Ingrese una cadena de caracteres: ")
    str2 = input("Ingrese otra cadena de caracteres: ")
    break


for i in str1:
    lista.append(i)
    
for j in str2:
    lista.insert(k, j)
    k += 2

print(lista)

Ingrese una cadena de caracteres: Hola Caracola
Ingrese otra cadena de caracteres: Adios Marieta
['H', 'A', 'o', 'd', 'l', 'i', 'a', 'o', ' ', 's', 'C', ' ', 'a', 'M', 'r', 'a', 'a', 'r', 'c', 'i', 'o', 'e', 'l', 't', 'a', 'a']


### Ejercicio 3 
Crea un programa que lea un string y guarde en una lista todas las consonantes.

In [22]:
string = input("Ingrese una secuencia de caracteres: ").lower()
vocales = ["a", "e", "i", "o", "u"]
consonantes = []

for i in string:
    if i not in vocales:
        consonantes.append(i)
print(consonantes)

Ingrese una secuencia de caracteres: Hola
['h', 'l']


### Ejercicio 4
Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.

In [60]:
palabra = list(input("Ingrese una palabra: ").lower())
pal = []

for i in palabra:
    pal.append(i)

pal.reverse()

if palabra == pal:
    print("La palabra {} es un palíndromo.".format(palabra))
else:
    print("La palabra {} no es un palíndromo.".format(palabra))

Ingrese una palabra: hola
La palabra ['h', 'o', 'l', 'a'] no es un palíndromo.


### Ejercicio 5
Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

In [22]:
M = []

for i in range(3):
    M.append([])
    for j in range(3):
        M[i].append(float(input("Ingresa el elemento ({}, {}). ".format(i,j))))
        
for row in M:
    print("El valor máximo de la fila {} es {}.".format(row, max(row)))

Ingresa el elemento (0, 0). 5
Ingresa el elemento (0, 1). 9
Ingresa el elemento (0, 2). 7
Ingresa el elemento (1, 0). 5
Ingresa el elemento (1, 1). 61
Ingresa el elemento (1, 2). 2
Ingresa el elemento (2, 0). 5
Ingresa el elemento (2, 1). 36
Ingresa el elemento (2, 2). 54
El valor máximo de la fila [5.0, 9.0, 7.0] es 9.0.
El valor máximo de la fila [5.0, 61.0, 2.0] es 61.0.
El valor máximo de la fila [5.0, 36.0, 54.0] es 54.0.


### Ejercicio 6
Crea un programa que lea un entero, $n$, de teclado y construya una matriz de tamaño $n × n$. Cada posición
debe contener su orden en la matriz (desde 0 hasta $n^2 − 1$). Por ejemplo, si $n$ es 3, deberá crearse la matriz
\begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\end{bmatrix}

In [143]:
M = []
n = int(input("Ingrese un número entero: "))
k = 0

while k <= (n**2 - 1):
    for i in range(n):
        M.append([])
        for j in range(n):
            M[i].append(k)
            k += 1
            print(M[i][j], end=" ")
        print("")

Ingrese un número entero: 3
0 1 2 
3 4 5 
6 7 8 


### Ejercicio 7
Crea una matriz de $n × m$ y asigna los valores manualmente. El programa debe indicar si la suma de cada
columna es el mismo valor.

In [21]:
matriz = []
n = int(input("Ingrese el número de filas para la matriz: "))
m = int(input("Ingrese el número de columnas para la matriz: "))
suma = 0
total = []

for i in range(n):
    matriz.append([])
    for j in range(m):
        matriz[i].append(float(input("Ingresa el elemento ({}, {}): ".format(i,j))))

for a in range(m):
    for b in range(n):
        suma = suma + matriz[b][a]
        b = + 1
    total.append(suma)
    suma = 0 
    a = + 1

    
                    
for i in range(n):
    for j in range(m):
        print(matriz[i][j], end = "  " if matriz[i][j] >= 0 else " ")
    print("")            

print(total)

Ingrese el número de filas para la matriz: 5
Ingrese el número de columnas para la matriz: 3
Ingresa el elemento (0, 0): 2
Ingresa el elemento (0, 1): 5
Ingresa el elemento (0, 2): 8
Ingresa el elemento (1, 0): 2
Ingresa el elemento (1, 1): 5
Ingresa el elemento (1, 2): 8
Ingresa el elemento (2, 0): 2
Ingresa el elemento (2, 1): 5
Ingresa el elemento (2, 2): 8
Ingresa el elemento (3, 0): 2
Ingresa el elemento (3, 1): 5
Ingresa el elemento (3, 2): 8
Ingresa el elemento (4, 0): 2
Ingresa el elemento (4, 1): 5
Ingresa el elemento (4, 2): 8
2.0  5.0  8.0  
2.0  5.0  8.0  
2.0  5.0  8.0  
2.0  5.0  8.0  
2.0  5.0  8.0  
[10.0, 25.0, 40.0]


### Ejercicio 8
Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos)
se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

In [65]:
matriz = []
n = int(input("Ingrese el número de filas para la matriz: ")) 
m = int(input("Ingrese el número de columnas para la matriz: ")) 
idt = True


for i in range(n):
    matriz.append([])
    for j in range(m):
        matriz[i].append(float(input("Ingresa el elemento ({}, {}): ".format(i,j))))
        
for i in range(n):
    for j in range(m):
        print(matriz[i][j], end = "  " if matriz[i][j] >= 0 else " ")
    print("")            

if n == m:
    for i in range(n):
        for j in range(n):
            if i == j and matriz[i][j] != 1:
                idt = False
            if i != j and matriz[i][j] != 0:
                idt = False
                
else:
    idt = False
    print("La matriz ingresada no es la matriz identidad porque no es cuadrada.")
    
print("¿La matriz ingresada es la matriz identidad? {} ".format(idt))


Ingrese el número de filas para la matriz: 3
Ingrese el número de columnas para la matriz: 3
Ingresa el elemento (0, 0): 1
Ingresa el elemento (0, 1): 0
Ingresa el elemento (0, 2): 0
Ingresa el elemento (1, 0): 0
Ingresa el elemento (1, 1): 1
Ingresa el elemento (1, 2): 0
Ingresa el elemento (2, 0): 0
Ingresa el elemento (2, 1): 0
Ingresa el elemento (2, 2): 1
1.0  0.0  0.0  
0.0  1.0  0.0  
0.0  0.0  1.0  
¿La matriz ingresada es la matriz identidad? True 


### Ejercicio 9
Realiza un programa que calcule la matriz transpuesta.

In [70]:
matr = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]

trans = []
for i in range(len(matr[0])):
    trans.append([])
    for j in range(len(matr)):
        trans[i].append(matr[j][i])
        
for i in range(len(trans)):
    for j in range(len(trans[0])):
        print(trans[i][j], end = "  " if trans[i][j] >= 0 else " ")
    print("")

1  4  7  
2  5  8  
3  6  9  


### Ejercicio 10
Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
numpy.

In [73]:
import numpy as np
n = int(input())
ident = np.zeros((n, n))
for i in range(n):
    ident[i, i] = 1
print(ident)

3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
