# Tarea 6 - Estructuras de datos: Diccionarios

#### Curso Python de la A a la Z

### Ejercicio 1
Crea un programa que pida un número entero positivo por teclado y que cree un diccionario cuyas claves
sean desde el número 1 hasta el número indicado. Los valores de cada clave serán las propias claves elevadas
al cubo.

In [19]:
limite = int(input("Ingrese el número límite para el diccionario: "))
clave = []
valor = []

for i in range(1, limite + 1):
    clave.append(i)
    valor.append(i**3)

dicc = {clave[i] : valor[i] for i in range(len(clave))}
print(dicc)

Ingrese el número límite para el diccionario: 8
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512}


##### Solución curso:

In [30]:
n = int(input("Introduce un número entero positivo: "))

d = {}
for i in range(1, n + 1):
    d[i] = i ** 3

print(d)

Introduce un número entero positivo: 5
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}


### Ejercicio 2
Escribe un programa que pregunte al usuario su nombre, edad y teléfono y lo guarde en un diccionario.
Después, debe mostrar por pantalla el mensaje  "{nombre} tiene {edad} años y su número de teléfono es
{teléfono}".

In [29]:
nombre = input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: "))
telefono = input("Ingrese su número de teléfono: ")

dicc = {"Nombre" : nombre, "Edad" : edad, "Teléfono" : telefono}

print(dicc.get("Nombre"), "tiene", dicc.get("Edad"), "años y su teléfono es", dicc.get("Teléfono"))

Ingrese su nombre: Claudia
Ingrese su edad: 29
Ingrese su número de teléfono: 22222222
Claudia tiene 29 años y su teléfono es 22222222


##### Solución curso:

In [31]:
user = {}

user["name"] = str(input("Introduce tu nombre: "))
user["age"] = int(input("Introduce tu edad: "))
user["phone"] = int(input("Introduce tu número de teléfono: "))

print("{} tiene {} años y su número de teléfono es {}.".format(user["name"], user["age"], user["phone"]))

Introduce tu nombre: Claudia
Introduce tu edad: 29
Introduce tu número de teléfono: 3108261507
Claudia tiene 29 años y su número de teléfono es 3108261507


### Ejercicio 3
Escribe un programa que cree un diccionario simulando una cesta de la compra. El programa debe preguntar
el artículo y su precio por unidad. El artículo será la clave y el valor el precio, hasta que el usuario decida
terminar. Después se debe mostrar por pantalla la lista de la compra y el coste total, con el siguiente formato

|            |        |
|------------|--------|
| Artículo 1 | Precio |
| Artículo 2 | Precio |
| Artículo 3 | Precio |
|------------|--------|
| Total | Total Precio |
|            |        |


In [50]:
cesta = {}
art = input("Ingresa el artículo: ")
total = 0
while art != "0":
    cesta[art] = float(input("Ingresa el precio del artículo: "))
    art = input("Ingresa el artículo: ")
print("")
for art, precio in cesta.items():
    total += precio
    print(art[0:5], "|", precio)
print(15*".")
print("Total", "|", total)

Ingresa el artículo Huevos
Ingresa el precio del artículo 4500
Ingresa el artículo Leche
Ingresa el precio del artículo 5454
Ingresa el artículo Pan
Ingresa el precio del artículo 5000
Ingresa el artículo 0

Huevo | 4500.0
Leche | 5454.0
Pan | 5000.0
...............
Total | 14954.0


##### Solución curso:

In [46]:
shopping_list = {}
key = input("Indica el artículo: ")

while key != "":
    shopping_list[key] = float(input("Indica l precio: "))
    key = input("Indica el artículo: ")

print("")
for key, val in shopping_list.items():
    print("|" + " " * (20 - 2 - len(key)) + key + " | " + str(val) + " " * (9 - len(str(val))) + "|")

Indica el artículo Huevos
Indica l precio 5000
Indica el artículo Leche
Indica l precio 5844
Indica el artículo Carne
Indica l precio 4545
Indica el artículo adasdas
Indica l precio 2000
Indica el artículo 

|            Huevos | 5000.0   |
|             Leche | 5844.0   |
|             Carne | 4545.0   |
|           adasdas | 2000.0   |


### Ejercicio 4
Crea un programa que lea números enteros hasta que introduzca el 0 y devuelva un diccionario con la
cantidad números positivos y negativos introducidos.

In [52]:
num = int(input("Ingresa un número entero: "))
positivo = 0
negativo = 0

while num != 0:
    if num > 0:
        positivo += 1
    else:
        negativo += 1
    num = int(input("Ingresa un número entero: "))
    
dicc = {"Positivos" : positivo, "Negativos" : negativo}
print(dicc)

Ingresa un número entero 5
Ingresa un número entero 6
Ingresa un número entero 4
Ingresa un número entero -5
Ingresa un número entero 45
Ingresa un número entero -85
Ingresa un número entero 0
{'Positivos': 4, 'Negativos': 2}


### Ejercicio 5
Crea un programa que lea números enteros hasta que introduzca el 0 y devuelva un diccionario con la
cantidad números pares e impares introducidos.

In [53]:
num = int(input("Ingresa un número entero: "))
par = 0
impar = 0

while num != 0:
    if num % 2 == 0:
        par += 1
    else:
        impar += 1
    num = int(input("Ingresa un número entero: "))
    
dicc = {"Pares" : par, "Impares" : impar}
print(dicc)

Ingresa un número entero 5
Ingresa un número entero 6
Ingresa un número entero 8
Ingresa un número entero 8
Ingresa un número entero 8
Ingresa un número entero 3
Ingresa un número entero 291
Ingresa un número entero 0
{'Pares': 4, 'Impares': 3}


### Ejercicio 6
Crea un programa que permita al usuario introducir los nombres de los alumnos de una clase y las notas que
han obtenido. Cada alumno puede tener distinta cantidad de notas. Guarda la información en un diccionario
cuyas claves serán los nombres de los alumnos y los valores serán listas con las notas de cada alumno.

El programa va a pedir el número de alumnos que vamos a introducir, pedirá su nombre e irá pidiendo sus
notas hasta que introduzcamos un número negativo. Al final el programa nos mostrará la lista de alumnos
y la nota media obtenida por cada uno de ellos.

PISTA: Vas a necesitar la función sum().


In [61]:
dicc = {}
alumno = input("Ingrese el nombre del alumno: ")

while alumno != "":
    dicc[alumno] = []
    notas = int(input("Ingresa las notas del estudiante: "))
    while notas > 0:
        dicc[alumno].append(notas)
        notas = int(input("Ingresa las notas del estudiante: "))
    alumno = input("Ingrese el nombre del alumno: ")
print("")

for i in dicc:
    print(i, ":", sum(dicc[i])/len(dicc[i]))



Ingrese el nombre del alumno fdfd
Ingresa las notas del estudiante 5
Ingresa las notas del estudiante 5
Ingresa las notas del estudiante 5
Ingresa las notas del estudiante 5
Ingresa las notas del estudiante 6
Ingresa las notas del estudiante 0
Ingrese el nombre del alumno fdfs
Ingresa las notas del estudiante 5
Ingresa las notas del estudiante 6
Ingresa las notas del estudiante 6
Ingresa las notas del estudiante 6
Ingresa las notas del estudiante 6
Ingresa las notas del estudiante 0
Ingrese el nombre del alumno 

fdfd : 5.2
fdfs : 5.8


### Ejercicio 7
Crea un programa que pida un número entero positivo por teclado y que cree un diccionario cuyas claves
sean desde el número 1 hasta el número indicado. Los valores de cada clave serán tantos símbolos "*" como
indique la clave.

In [62]:
num = int(input("Ingresa un número entero: "))
dicc = {}

for i in range(1, num + 1):
    dicc[i] = i * "*"

print(dicc)

Ingresa un número entero 5
{1: '*', 2: '**', 3: '***', 4: '****', 5: '*****'}


### Ejercicio 8
Crea un programa que pida el número de palabras a introducir. Crear un diccionario de clave la palabra y
de valor la longitud de dicha palabra.


In [64]:
numpal = int(input("Ingrese el número de palabras deseadas: "))
dicc = {}

for i in range(numpal):
    palabra = input("Ingrese la palabra deseada: ")
    dicc[palabra] = len(palabra)

print(dicc)

Ingrese el número de palabras deseadas 3
Ingrese la palabra deseada Claudia
Ingrese la palabra deseada Ospina
Ingrese la palabra deseada Grajales
{'Claudia': 7, 'Ospina': 6, 'Grajales': 8}


### Ejercicio 9
Crea un programa que pida el número de palabras a introducir. Crear un diccionario de clave la palabra y
de valor el número de vocales de la palabra.

In [66]:
numpal = int(input("Ingrese el número de palabras deseadas: "))
dicc = {}
vocal = ["a", "e", "i", "o", "u"]

for i in range(numpal):
    palabra = input("Ingrese la palabra deseada: ").lower()
    vocales = 0
    for letra in palabra:
        if letra in vocal:
            vocales += 1
    dicc[palabra] = vocales

print(dicc)

Ingrese el número de palabras deseadas: 3
Ingrese la palabra deseada: Claudia
Ingrese la palabra deseada: Ospina
Ingrese la palabra deseada: Grajales
{'claudia': 4, 'ospina': 3, 'grajales': 3}


### Ejercicio 10
Dada una matriz, crea un diccionario que guarde el número de filas, el de columnas y cada fila en una entrada
de un diccionario.

In [68]:
import numpy as np
matriz = np.random.rand(3, 4)
print(matriz)

dicc = {"Filas": len(matriz), "Columnas": len(matriz[0])}
print(dicc)

[[0.45778896 0.27687473 0.15682104 0.14742168]
 [0.08143394 0.36633248 0.80513423 0.46419732]
 [0.15083162 0.66678566 0.49618669 0.74797983]]
{'Filas': 3, 'Columnas': 4}
